name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "hAve A nice dAy"
      - name: Print Goodbye
        run: echo "Its BreAkup"
    
